# Generated by Django 3.1.3 on 2020-12-17 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.CharField(max_length=1000)),
                ('multiselect', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('phase', models.PositiveSmallIntegerField(
                    choices=[(1, 'Phase-1'), (2, 'Phase-2'), (3, 'Phase-3'), (4, 'Phase-4')], default=1)),
                ('root',
                 models.BooleanField(default=False, help_text='Note that you cannot delete the root questionnaire.')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questionnaire_responses',
                                   to='questionnaire.questionnaire')),
            ],
        ),
    ]
