# Generated by Django 3.1.3 on 2020-12-21 17:51

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('users', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='student_profile_responses', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question',
                                    to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='option',
            name='continuation_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='from_options', to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option',
                                    to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='option',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True,
                                                  help_text='Enter a comma-separated tag string',
                                                  related_name='options', to='tag.Tag', tree=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='option_responses',
                                    to='questionnaire.option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='question_responses',
                                    to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                    to='questionnaire.questionnaireresponse'),
        ),
    ]
