# Generated by Django 3.1.3 on 2021-02-23 18:39

from django.db import migrations

from generate_questionnaire_migration import generate_questionnaire


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210224_0002'),
    ]

    operations = [
        migrations.RunPython(generate_questionnaire)
    ]
