# Generated by Django 3.1.3 on 2020-12-17 20:16

from django.db import migrations

from generate_questionnaire_migration import generate_questionnaire


class Migration(migrations.Migration):
    dependencies = [
        ('questionnaire', '0002_auto_20201218_0126'),
    ]

    operations = [
        migrations.RunPython(generate_questionnaire)
    ]
