# Generated by Django 3.1.3 on 2020-12-21 17:55

from django.db import migrations

from generate_questionnaire_migration import generate_questionnaire


class Migration(migrations.Migration):
    dependencies = [
        ('questionnaire', '0002_auto_20201221_2321'),
    ]

    operations = [
        migrations.RunPython(generate_questionnaire)
    ]
