# Generated by Django 3.1.3 on 2021-02-23 19:11

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=512, null=True, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Article'), (2, 'Course'), (3, 'Job'), (4, 'Project')], default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', django_bleach.models.BleachField()),
                ('preview', models.CharField(help_text='A short preview of this post that is shown in list of posts.', max_length=300)),
                ('allow_comments', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='student_uploads/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_submissions', to='blog.post')),
            ],
        ),
    ]
