# Generated by Django 3.1.3 on 2020-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20201218_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
