# Generated by Django 3.1.3 on 2020-12-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('blog', '0002_auto_20201221_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='users.studentprofile'),
        ),
    ]
