# Generated by Django 3.1.3 on 2020-12-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('blog', '0003_auto_20201222_0053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student_profile', 'post')},
        ),
    ]
