# Generated by Django 3.1.3 on 2020-12-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_submissions',
                                    to='blog.post', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
