from django.urls import path, include
from . import views

urlpatterns = [
    path('next_questionnaire/', views.next_questionnaire, name='api-questionnaire-next-questionnaire'),
    path('submit_questionnaire_response/', views.submit_questionnaire_response,
         name='api-questionnaire-submit-questionnaire-response'),
    path('reset_questionnaire_responses/', views.reset_questionnaire_responses,
         name='api-questionnaire-reset-questionnaire-responses'),
    path('get_all_questionnaires/', views.get_all_questionnaires,
         name='api-questionnaire-get-all-questionnaires'),
    path('update_questionnaire/', views.update_questionnaire,
         name='api-questionnaire-update-questionnaire'),
    path('add_questionnaire/', views.add_questionnaire,
         name='api-questionnaire-add-questionnaire'),
    path('delete_questionnaire/', views.delete_questionnaire,
         name='api-questionnaire-delete-questionnaire'),
    path('update_question/', views.update_question,
         name='api-question-update-question'),
    path('add_question/', views.add_question,
         name='api-question-add-question'),
    path('delete_question/', views.delete_question,
         name='api-question-delete-question'),
    path('update_option/', views.update_option,
         name='api-option-update-option'),
    path('add_option/', views.add_option,
         name='api-option-add-option'),
    path('delete_option/', views.delete_option,
         name='api-option-delete-option'),
]
